# Copyright 2015 clair authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
introspection_addr: ":8081"
http_listen_addr: ":8080"
log_level: debug
indexer:
  #connstring: host=localhost port=5432 user=clair dbname=clair sslmode=disable
  connstring: host=postgres port=5432 user=postgres password=password sslmode=disable statement_timeout=60000
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  #connstring: host=localhost port=5432 user=clair dbname=clair sslmode=disable
  connstring: host=postgres port=5432 user=postgres password=password sslmode=disable statement_timeout=60000
  max_conn_pool: 100
  migrations: true
matchers: {}
notifier:
  #connstring: host=localhost port=5432 user=clair dbname=clair sslmode=disable
  connstring: host=postgres port=5432 user=postgres password=password sslmode=disable statement_timeout=60000
  migrations: true
  delivery_interval: 1m
  poll_interval: 5m
